image: python:latest

pages:
  stage: deploy
  only:
    - release/0.9.0
  script:
    - pip install mkdocs-material
    - pip install mkdocs-macros-plugin
    - pip install mkdocs-enumerate-headings-plugin
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public

🤔pages:preview:
  stage: deploy
  script:
    - pip install mkdocs-material
    - pip install mkdocs-macros-plugin
    - pip install mkdocs-enumerate-headings-plugin
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_MERGE_REQUEST_IID
  environment:
    name: preview/${CI_PROJECT_NAME}/${CI_COMMIT_REF_NAME}
    url: https://${CI_PROJECT_NAMESPACE}.gitlab.io/-/gl-pages/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/public/index.html
    on_stop: 😢pages:preview:stop
  
😢pages:preview:stop:
  stage: deploy
  rules:
    - if: $CI_MERGE_REQUEST_IID
      when: manual
  allow_failure: true
  environment:
    name: preview/${CI_PROJECT_NAME}/${CI_COMMIT_REF_NAME}
    action: stop
  script:
    - echo "👋 bye"
